### ISSUE TITLE
RFC draft expired

### ISSUE THREAD

**Issue by xorhash** [paragonie/paseto#108]
https://tools.ietf.org/html/draft-paragon-paseto-rfc-00 notes: “Expires: October 21, 2018” No new draft seems to have been submitted yet. This may need updating.

**Comment by ishrivatsa** [comment]
Was this converted to a standard ? I can find only the draft submission.

**Comment by paragonie-security** [comment]
No, it depends on the XChaCha draft first.

**Comment by ishrivatsa** [comment]
Thanks for the quick response. I noticed that the draft for that is expiring this month (JAN 2020). Will it be extended?  The reason I am asking is I would like to implement this within my application but wanted to see a roadmap of PASETO becoming a standard :)

**Comment by paragonie-security** [comment]
XChaCha was supposed to be reviewed for standardization in 2019. We'll bug the CFRG to get this in motion as soon as we can for 2020.

Once XChaCha is an Internet standard, we'll review some of the feedback we've received from the cryptography community, amend the RFC draft, and then issue a follow-up PASETO draft.

**Comment by ishrivatsa** [comment]
Thanks for the update. This helps.

**Comment by fkooman** [comment]
[XChaCha: eXtended-nonce ChaCha and AEAD_XChaCha20_Poly1305](https://tools.ietf.org/html/draft-irtf-cfrg-xchacha-01)

**Comment by paragonie-security** [comment]
Now it's at https://tools.ietf.org/html/draft-irtf-cfrg-xchacha-02

CFRG thread: https://mailarchive.ietf.org/arch/msg/cfrg/coaC68uPo1nD_3rrjSh8UzHTevM

**Comment by xorhash** [comment]
I don't think you *need* to stall PASETO efforts. E.g. the [BLS I-D](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-00) has apparently no issues continuing while the hash-to-point I-D is still a draft.

**Comment by paragonie-security** [comment]
Speaking from experience dealing with open source communities and political decisions thereof...

IETF members can and will use "but XChaCha isn't an RFC yet!" to stall a PASETO RFC, because it competes with JOSE (which is inexplicably popular for some reason), even in the presence of a congruent counterexample. The same logic does not necessarily need to hold for other projects.

In our experience, we've discovered that community/group dynamics do not have to be logically consistent, and expecting them to be will just lead to any efforts we start being dead in the water. 

The best course of action is to assume the worst and plan accordingly. That's how we've been able to make changes to the PHP core, to WordPress, and (thus far) with the IETF.

**Comment by cristaloleg** [comment]
> Now it's at tools.ietf.org/html/draft-irtf-cfrg-xchacha-02

Well, it's also expired: `Expires: July 13, 2020` @paragonie-security

**Comment by paragonie-security** [comment]
We intend to revisit this in the near future.

**Comment by paragonie-security** [comment]
* The specification lives here: https://github.com/paseto-standard/paseto-spec
* The RFC draft lives here: https://github.com/paseto-standard/paseto-rfc

I'm going to close this issue. If you don't hear about a PASETO RFC in the next few months, please feel free to open an issue in one or both of those repositories.
