### ISSUE TITLE
paseto.io website

### ISSUE THREAD

**Issue by rlittlefield** [paragonie/paseto#60]
I noticed that paseto.io is registered and currently just points to chronicle. I'm not sure if there are any plans yet. I think some of JWT's usage/success is driven from the utility and visibility of that marketing-style site.

Some ideas:

- token sandbox
- curated list of implementations with feature matrix (v1,v2,public,local,registered claims)
- link to reference implementation
- mirror for the RFC
- examples of valid use-cases
- documentation of what not to do / why paseto vs jwt (maybe even link to the paragonie blog)
- list of projects using paseto (non libraries) in a non abhorrent way

**Comment by paragonie-scott** [comment]
Eventually. I just have it pointing to the pie-hosted.com server, but there's no vhost configured for it.

**Comment by SecurityInsanity** [comment]
I notice this is tagged as "Help Wanted", can you perhaps outline what we as a community can do to help? Would you like PRs to this repo, just some ideas in this issue, or something else entirely?

**Comment by paragonie-scott** [comment]
@SecurityInsanity In the coming weeks, I plan on creating a simple website that pulls from a public Github repository, which will hopefully do some or all of the things @rlittlefield listed above.

However, my graphics/web design skills are abysmal and trying to improve them through experience mostly results in people on Twitter/Reddit/HN telling you you're awful in the least actionable way possible. ("This is ugly." "What would you change?" "You should really hire a designer instead of trying to learn.")

**Comment by SecurityInsanity** [comment]
Alright, well let me know when you get that setup @paragonie-scott , I know we have some people would love to help spruce it up a bit/review.

**Comment by paragonie-scott** [comment]
http://paseto.io (no HTTPS yet because I ran head-first into the LetsEncrypt rate limit while tripping over a DNS issue and probably have to wait a week for it to be resolved)

https://github.com/paragonie/paseto-io
